export enum BookingStatus {
  DRAFT = 'DRAFT',
  WAITING_FOR_OFFERS = 'WAITING_FOR_OFFERS',
  UNDER_NEGOTIATION = 'UNDER_NEGOTIATION',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  CONFIRMED = 'CONFIRMED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}