export enum AccountStatus {
  CREATED = 'CREATED',
  PENDING_OTP = 'PENDING_OTP',
  PENDING_REVIEW = 'PENDING_REVIEW',
  OFFICE_NO_SUBSCRIPTION = 'OFFICE_NO_SUBSCRIPTION',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  BLOCKED = 'BLOCKED',
}